[package]
name = "llamavision"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0", features = [ "backtrace" ] }
atomic-wait = "1.1.0"
clap = { version = "4", features = ["derive"] }
fftw = { version = "0.8.0", default-features = false, features = ["system"] }
lerp = "0.5"
pipewire = "0.8.0"
sdl3 = { version = "0.18.4", features = [ "use-pkg-config" ] }
tinyvec = "1.8.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
